[package]
name = "polymarket-api"
version = "0.1.0"
edition = "2021"
description = "Polymarket API client"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/DenisGorbachev/polymarket-api"
repository = "https://github.com/DenisGorbachev/polymarket-api"
readme = "README.md"
keywords = ["polymarket", "api"]
categories = ["api-bindings"]

[package.metadata.details]
title = "Polymarket API client"
tagline = ""
summary = ""
announcement = ""

[dependencies]
alloy = { version = "0.5.0", default-features = false, features = ["std", "serde"] }
async-stream = { version = "0.3.6" }
derive-getters = { version = "0.5.0", features = ["auto_copy_getters"] }
derive-new = "0.7.0"
derive_more = { version = "1.0.0", features = ["full"] }
fmt-derive = { version = "0.1.2" }
futures = { version = "0.3.30" }
indexmap = { version = "2.6.0" }
reqwest = { version = "0.12.8", features = ["json"] }
rust_decimal = { version = "1.36.0", features = ["serde"] }
rustc-hash = { version = "2.0.0" }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = { version = "1.0.132" }
#standard-traits = { git = "https://github.com/DenisGorbachev/standard-traits" }
stub-macro = "0.1.6"
subtype = { git = "https://github.com/DenisGorbachev/subtype" }
time = { version = "0.3.36", features = ["serde", "macros", "formatting", "parsing"] }
url = { version = "2.5.2", features = ["serde"] }
url-macro = { version = "0.1.9" }

[dev-dependencies]
env_logger = "0.11.5"
serde_json = "1.0.129"
tokio = { version = "1.39.2", features = ["macros", "fs", "net", "rt", "rt-multi-thread"] }

[package.metadata.cargo-machete]
ignored = ["stub_macro"]
